ClassicPress/ClassicPress-Migration-Plugin

- .gitignore
- .lando.yml
- .travis.yml
- test/install-wp-cli.sh
- test/lando-setup.sh
- test/lando-tail-logs.sh
We need fairly extensive automated QA for this plugin, covering multiple PHP and WP versions, so it's best to go ahead and set that up as soon as possible.
So far, I'm using [`lando`](https://github.com/lando/lando) to spin up a WP site and install the plugin.  This automated setup has made it much easier to develop the plugin locally, and the PHP and WP versions are configurable.
First, make sure this setup works on Travis.
Then, I'll use [`puppeteer`](https://github.com/GoogleChrome/puppeteer) to simulate logging in to the site and performing the upgrade, and make sure the results are as expected.
Finally we can build out a test matrix for various combinations of versions, features, etc.
It might also be a good idea to add a test for a "normal" WP upgrade and make sure the plugin …
> Set up Travis CI

- lib/admin-page.php
This PR aims to prevent multiple clicks on the Migrate button, which is a potential cause for this error:
> Another update is currently in progress.
In order to continue sending the `upgrade` value from the form, which is [required](https://github.com/ClassicPress/ClassicPress/blob/ced817fd49e84f0efa646591e1faa941ca5a83bd/src/wp-admin/update-core.php#L695) for the upgrade process to trigger, we need to add a new `<input type="hidden">` element because [disabled elements are not submitted as part of a form](https://stackoverflow.com/questions/1355728/values-of-disabled-inputs-will-not-be-submitted).
cc: @ginsterbusch
> Prevent multiple clicks on the Migrate button

- lib/admin-page.php
- lib/check-core-files.php
So far only `composer.json` - seems to work.
> A basic check for known-conflicting files

- lib/admin-page.php
- lib/update.php
Further steps towards issue #27 (restore the previous version of WordPress).
This is **pre-alpha** functionality - do not run it on sites you care about!  Accordingly, the form has `class="hidden"` which you must remove yourself in order to test this.
To show the form:
- Ensure you are running ClassicPress
- Visit the Switch to ClassicPress plugin page
- Paste the following JavaScript snippet in the developer console and run it:
```js
jQuery('#cp-advanced-migration-form').removeClass('hidden')
```
To use it, enter a valid build URL ~and version~ (for example `https://wordpress.org/wordpress-4.9.9.zip` ~and `4.9.9`~).
~**Important limitation:** this code (and the migration plugin in general) cannot migrate to all official release builds of ClassicPress, only builds that are specifically …
> Enable migrating from ClassicPress to anything

- lib/admin-page.php
- lib/update.php
- switch-to-classicpress.php
Fetch the following data from https://api-v1.classicpress.net/migration/ instead of hard-coding it in each version of the migration plugin:
- Supported WordPress versions
- Target ClassicPress build URL and version
Most new versions of WordPress or ClassicPress do not require changes to the migration plugin.  In the future moving the version data to an API endpoint will allow us to keep the migration plugin up to date without requiring a new release of the plugin.
See also:
- https://github.com/ClassicPress/ClassicPress-APIs/blob/87b3354/v1/migration/index.php
- https://forums.classicpress.net/t/small-migration-frustration/981
> Move version parameters to an API endpoint

- lib/update.php
After running a custom migration the following notice often appears:
> ClassicPress _custom_migration is available! Please update now.
This PR fixes the issue by checking for cached update data matching this pattern and removing it:
- when visiting the About page in the dashboard, which is the first screen shown after an update/migration.
- when visiting the Dashboard > Updates page, just in case this update data needs to be cleared out manually for whatever reason.
This check could also be done on every admin page, but this would involve an extra database query so I think it's probably not worth it.
Fixes #62.
> Fix invalid upgrade notices after a custom migration

- README.md
At present, it is not immediately clear which versions of WordPress are supported by the migration plugin.
This small update to `README.md` makes it much easier to find that information.
As things stand, the WP version will need to be updated manually on each new release of the plugin.
> Add note to README.md about compatible WP versions

- lib/admin-page.php
This PR adds compatibility sections that check for known incompatible plugins active on an install and also for incompatible theme in use (Twenty Twenty-One)
This change is contingent on an update to the migrate API, for which there is already a PR.
https://github.com/ClassicPress/ClassicPress-APIs/pull/24
> Add Plugin and Theme check sections

- lib/admin-page.php
We currently have a string in the Migration plugin that directs users to their Hosting Provider when migrations cannot proceed.
Instead, and as per #81, we should direct migrators to our own forums.
> Direct blocking issues to ClassicPress Forum

- lib/admin-page.php
- switch-to-classicpress.php
This patch will scan plugin headers for plugins declaring a requirement for WordPress 5.0 and above.
If adopted, this fixes #77
> Add plugin header checking

- lib/admin-page.php
This PR adds a compatibility check to Theme Headers to check the value is not 5.0 or above.
It may need more work to assess what happens if that header is not present.
> Add theme header comparison check to compatibility logic

- switch-to-classicpress.php
Version numbers should be bumped when updating the plugin.
Note, now due to the semver it cannot be 1.4.0 but must be 1.4.1
> Bump Version number

- lib/admin-page.php
Some of the recent additional checks added to the plugin are not styled to the same size and I figured out it was due to some missing paragraph tags.
This PR fixes the styling to ensure all user reports data is displayed in the same text size.
> Add HTML paragraph tags to ensure consistent text size display

- lib/admin-page.php
See also:
https://github.com/ClassicPress/ClassicPress-APIs/pull/31
This PR alters checking of supported PHP versions to utilise data from the migration API endpoint with the aim of stopping migration on WordPress sites that are using PHP version 8.0 and higher.
> Implement PHP version checking based on migration API endpoint

- lib/check-core-files.php
This is a possible fix for #95, core file changes are reported if wp-config-sample.php is missing, perhaps we should not report that as an issue when migrating.
> Possible fix for #95

- lib/admin-page.php
This has already been discussed a little elsewhere:
https://github.com/ClassicPress/ClassicPress-Migration-Plugin/pull/90
Some `asset()` checks have been added to the plugin during development to ensure local code worked while the API endpoint was still in need of amendment.
These checks are probably unnecessary in the release version of the plugin. So this patch removes individual checks for the API data for more consistency through plugin and because there is a central API response check.
> Code tidy to remove some asset() checks

- lib/admin-page.php
- switch-to-classicpress.php
- Adjust checks, notifications and information text as needed for CP v2
- Warn that Migration requires Re-Install (reminder if you go back into the plugin)
- Chat link changed from Slack to Zulip
- Add smart drop down to Advanced Controls
- Offer CP v1 & v2 current and one version back (unless no previous as with 2 right now)
- Offer WP current, 6.3.x and 4.9.x (4.9 offered only if running php7)
- Offer release version if running CP migration version
- Will not offer what you already have
- Suggest CP Default theme (temporary hard coded - API needs adjustment)
> Migration Plugin Update

- lib/admin-page.php
This eliminates the following warning in the browser console:
```
Uncaught TypeError: document.getElementById(...) is null
```
> Update admin-page.php to eliminate console warning

- lib/admin-page.php
Headers must always descend sequentially. Since the previous header on the page for each of those changed in this PR is an `h1`, the two headers must be `h2`s.
Note that ascending headers do not need to be sequential.
> Update admin-page.php to change h3 headers to h2 for accessibility

- .github/workflows/cpcs.yml
> Add cpcs checks workflow

- README.md
- lib/admin-page.php
- switch-to-classicpress.php
- Change Plugin and Theme Checks to explain safest method, but only warn if not followed
- Change Core File check to show any modified files on the page rather than in the console
- Display override function info for unsupported WP versions when applicable
- Correct links and update wording as needed
- Bump version to 1.5.3
> Update to Plugin and Theme Warnings

- lib/admin-page.php
This adds a Ignore WordPress version checkbox in the General settings.
This is an alternative to add_filter( 'classicpress_ignore_wp_version', '__return_true' ); that is still in place.
Closes #98 .
> Add override for WP version check in "General setting"
